import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchDestinations = async () => {
  const response = await fetch(
    "https://raw.githubusercontent.com/Lstanislao/cities-permalink/main/flights.json"
  );
  if (!response.ok) {
    throw new Error("Failed to fetch destinations");
  }
  return response.json();
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const destinations = await fetchDestinations();
  return (
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-6 py-4`}
      >
        {children}
      </body>
    </html>
  );
}
